apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  namespace: rolloutdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
